// <auto-generated />
using System;
using HWAPI.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HWAPI.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20211106134853_firstM")]
    partial class firstM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("HWAPI.Models.Quotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Наполеон Хилл",
                            InsertDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Что разум человека может постигнуть и во что он может поверить, того он способен достичь"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Альберт Эйнштейн",
                            InsertDate = new DateTime(1890, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Стремитесь не к успеху, а к ценностям, которые он дает"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Достоевский",
                            InsertDate = new DateTime(1890, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Надо любить жизнь больше, чем смысл жизни."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Амелия Эрхарт",
                            InsertDate = new DateTime(1800, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Сложнее всего начать действовать, все остальное зависит только от упорства"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Борис Стругацкий",
                            InsertDate = new DateTime(1810, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Начинать всегда стоит с того, что сеет сомнения."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
